lib/encrypted_file_transfer_web/router.ex
defmodule EncryptedFileTransferWeb.Router do
  use EncryptedFileTransferWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EncryptedFileTransferWeb do
    pipe_through :browser

    get "/", EncryptedFileController, :new
    post "/", EncryptedFileController, :create
    get "/:id", EncryptedFileController, :show
    post "/download/:id", EncryptedFileController, :download
    delete "/:id", EncryptedFileController, :destroy
  end

  scope "/", EncryptedFileTransferWeb do
    pipe_through :api
  end
end

lib/encrypted_file_transfer/application.ex
defmodule EncryptedFileTransfer.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      EncryptedFileTransfer.Repo,
      # Start the endpoint when the application starts
      EncryptedFileTransferWeb.Endpoint,
      # Starts a worker by calling: EncryptedFileTransfer.Worker.start_link(arg)
      # {EncryptedFileTransfer.Worker, arg},
      {Phoenix.PubSub, [name: EncryptedFileTransfer.PubSub, adapter: Phoenix.PubSub.PG2]}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: EncryptedFileTransfer.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EncryptedFileTransferWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/encrypted_file_transfer/encrypted_file.ex
defmodule EncryptedFileTransfer.EncryptedFile do
  use Ecto.Schema
  import Ecto.Changeset
  alias Ecto.UUID, as: UUID
  alias EncryptedFileTransfer.FileStorageService

  @primary_key {:id, :binary_id, autogenerate: false}

  schema "encrypted_files" do
    field :extension, :string
    field :initialization_vector, :string
    field :encrypted_file, :map, virtual: true

    timestamps()
  end

  @doc false
  def changeset(file, attrs \\ %{}) do
    uuid = UUID.generate

    file
    |> cast(attrs, [:id, :extension, :initialization_vector, :encrypted_file])
    |> validate_required([:extension, :initialization_vector, :encrypted_file])
    |> set_id(uuid)
    |> upload_file()
  end

  defp set_id(struct, uuid) do
    put_change(struct, :id, uuid)
  end

  defp upload_file(struct) do
    file = get_field(struct, :encrypted_file)
    key = get_field(struct, :id)
    FileStorageService.upload(file, key)
    struct
  end
end

lib/encrypted_file_transfer/file_storage_service.ex
defmodule EncryptedFileTransfer.FileStorageService do
  def upload(nil, _key) do
    nil
  end

  def upload(upload_params, key) do
    file = upload_params.path
    file
      |> ExAws.S3.Upload.stream_file
      |> ExAws.S3.upload("/", key)
      |> ExAws.request!
  end

  def download(key) do
    ExAws.S3.get_object("/", key)
      |> ExAws.request
  end

  def destroy(key) do
    ExAws.S3.delete_object("/", key)
      |> ExAws.request
  end
end

lib/encrypted_file_transfer/repo.ex
defmodule EncryptedFileTransfer.Repo do
  use Ecto.Repo,
    otp_app: :encrypted_file_transfer,
    adapter: Ecto.Adapters.Postgres
end

lib/encrypted_file_transfer_web/controllers/encrypted_file_controller.ex
defmodule EncryptedFileTransferWeb.EncryptedFileController do
  use EncryptedFileTransferWeb, :controller
  alias EncryptedFileTransfer.EncryptedFile
  alias EncryptedFileTransfer.Repo
  alias EncryptedFileTransfer.FileStorageService

  def new(conn, _params) do
    changeset = EncryptedFile.changeset(%EncryptedFile{})
    render(conn, "new.html", changeset: changeset)
  end

  def show(conn, params) do
    id = params["id"]
    render(conn, "show.html", %{id: id})
  end

  def create(conn, params) do
    changeset = EncryptedFile.changeset(%EncryptedFile{}, params)

    case Repo.insert(changeset) do
      {:ok, file} ->
        conn
        |> put_status(:created)
        |> render("show.json", %{encrypted_file: file})
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render("error.json", changeset: changeset)
      end
  end

  def download(conn, params) do
    file = Repo.get(EncryptedFile, params["id"])

    case FileStorageService.download(~s(#{params["id"]})) do
      {:ok, encrypted_file} ->
        File.mkdir("priv/static/downloads")
        {:ok, downloaded_file} = File.open ~s(priv/static/downloads/#{params["id"]}), [:write]
        IO.binwrite downloaded_file, encrypted_file.body
        File.close downloaded_file

        conn
        |> put_status(:ok)
        |> render("show.json", %{encrypted_file: file})
      {:error} ->
        conn
        |> put_status(500)
        |> render("error.json")
    end
  end

  def destroy(conn, params) do
    case FileStorageService.destroy(~s(#{params["id"]})) do
      {:ok, _} ->
        File.rm!(~s(priv/static/downloads/#{params["id"]}))
        file_to_delete = Repo.get(EncryptedFile, params["id"])
        Repo.delete(file_to_delete)

        conn
        |> put_status(:ok)
        |> render("delete.json")
      {:error} ->
        conn
        |> put_status(500)
        |> render("error.json")
    end
  end

end

lib/encrypted_file_transfer_web/views/encrypted_file_view.ex
defmodule EncryptedFileTransferWeb.EncryptedFileView do
  use EncryptedFileTransferWeb, :view

  def render("show.json", %{encrypted_file: encrypted_file}) do
    render_one(encrypted_file, EncryptedFileTransferWeb.EncryptedFileView, "encrypted_file.json")
  end

  def render("encrypted_file.json", %{encrypted_file: encrypted_file}) do
    %{
      extension: encrypted_file.extension,
      id: encrypted_file.id,
      initialization_vector: encrypted_file.initialization_vector
    }
  end

  def render("delete.json", _assigns) do
    %{success: true}
  end
end

lib/encrypted_file_transfer_web/views/error_view.ex
defmodule EncryptedFileTransferWeb.ErrorView do
  use EncryptedFileTransferWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/encrypted_file_transfer_web/views/layout_view.ex
defmodule EncryptedFileTransferWeb.LayoutView do
  use EncryptedFileTransferWeb, :view
end

lib/encrypted_file_transfer_web/templates/encrypted_file/new.html.eex
<section class="content upload">
  <%= form_for @changeset, Routes.encrypted_file_path(@conn, :create), [class: "create-file-form"], fn _ -> %>
    <div class="error-message"></div>
    <ol class="steps">
      <li class="step choose-file-section">
        <strong class="step-order">1.</strong>
        <div class="step-content">
          <div class="choose-file-content">
            <div class="choose-file-wrapper">
              <div class="choose-file-button">
                <span class="description">Click to choose a file from your device or drag a file here</span>
                <input class="choose-file-input" type="file" name="file" />
              </div>
            </div>
            <div class="file-name-wrapper">
              <div class="choose-file-name"></div>
              <button class="choose-file-remove-button" type="button"><span class="icon"></span></button>
            </div>
          </div>
        </div>
      </li>
      <li class="step password-section">
        <strong class="step-order">2.</strong>
        <div class="step-content">
          <label class="password-input-label">Enter a password for your file:</label>
          <input class="password-input" type="password" name="password" placeholder="Password">
          <div class="password-hint">Must be at least 8 characters</div>
        </div>
      </li>
      <li class="step upload-button-section">
        <strong class="step-order">3.</strong>
        <div class="step-content">
          <label class="password-input-label">Upload your file:</label>
          <button class="upload-file-button" type="submit">Upload file</button>
          <button class="cancel-upload-button" type="button">Cancel</button>
        </div>
      </li>
      <li class="step upload-complete-section">
        <div class="success-message"></div>
      </li>
    </ol>
  <% end %>
</section>

lib/encrypted_file_transfer_web/templates/encrypted_file/show.html.eex
<section class="content download">
  <%= form_for @conn, Routes.encrypted_file_path(@conn, :download, @id), [class: "download-file-form"], fn _ -> %>
    <div class="error-message"></div>
    <div class="section password">
      <label class="password-input-label">Enter password:</label>
      <input class="password-input" type="password" name="password" placeholder="Password">
      <button class="download-file-button" type="submit">Download file</button>
    </div>
    <div class="section download-link">
      <div class="success-message"></div>
    </div>
  <% end %>
</section>

lib/encrypted_file_transfer_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Encrypted File Transfer</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/index.css") %>"/>
  </head>
  <body>
    <header class="header">
      <h1>
        <a href="/" class="logo">Encrypted File Transfer</a>
      </h1>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
      <div class="loader"></div>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/index.js") %>"></script>
  </body>
</html>